language: python
python:
    - "2.7"
install:
    - pip install coveralls
    - pip install matplotlib
    - pip install networkx
script:
    - coverage run --source=eight setup.py test
after_success:
    - coveralls
